import { Frame } from ".";

export default {
  title: "Components/Frame",
  component: Frame,
};

export const Default = {
  args: {
    className: {},
    maskGroupClassName: {},
    desktopClassName: {},
    headerHeaderClassName: {},
    aboutVector: "abc",
    aboutImg: "abc",
    aboutVector1: "abc",
    aboutVector2: "abc",
    aboutVector3: "abc",
    aboutVector4: "abc",
    aboutVector5: "abc",
    aboutVector6: "abc",
    aboutVector7: "abc",
    aboutVector8: "abc",
    aboutVector9: "abc",
    aboutFreepikCharacter: "abc",
    aboutVector10: "abc",
    aboutVector11: "abc",
    aboutVector12: "abc",
    aboutVector13: "abc",
    aboutVector14: "abc",
    aboutVector15: "abc",
    aboutFreepikShadows: "abc",
    aboutVector16: "abc",
    aboutVector17: "abc",
    aboutVector18: "abc",
    aboutVector19: "abc",
    aboutVector20: "abc",
    aboutVector21: "abc",
    aboutVector22: "abc",
    aboutVector23: "abc",
    aboutVector24: "abc",
    aboutFreepikPictures: "abc",
    aboutVector25: "abc",
    aboutFreepikPlantInject: "abc",
    aboutVector26: "abc",
    aboutVector27: "abc",
    aboutVector28: "abc",
    aboutVector29: "abc",
    aboutVector30: "abc",
    aboutVector31: "abc",
    aboutVector32: "abc",
    aboutVector33: "abc",
    aboutVector34: "abc",
    aboutVector35: "abc",
    aboutVector36: "abc",
    footerClassName: {},
  },
};
